- name: network lab
  hosts: all
  become: yes
  tasks:
  - name: install base tools
    apt:
      name:
        - traceroute
        - net-tools
      state: present
      update_cache: true
  - name: install tools for inetRouter
    apt:
      name:
        - iptables-persistent
      state: present
      update_cache: true
    when: (ansible_hostname == "inetRouter") 
  - name: disable ufw service
    service:
      name: ufw
      state: stopped
      enabled: false
    when: (ansible_hostname == "inetRouter")
  - name: Add rules
    shell: "iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE"
    when: (ansible_hostname == "inetRouter")
  - name: Save rules
    shell: "netfilter-persistent save"
    when: (ansible_hostname == "inetRouter")
  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
    when: "'routers' in group_names"
  - name: add default gateway for centralRouter
    template: 
      src: templates/"50-vagrant_{{ansible_hostname}}.yaml"
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
  - name: restart all hosts
    reboot:
      reboot_timeout: 600
